language: swift
osx_image: xcode12

deploy:
  provider: releases
  api_key: ${GITHUB_TOKEN}
  file_glob: true
  file:
    - "./artifacts/**/*"
  skip_cleanup: true
  on:
    all_branches: true
  on:
    tags: true

branches:
  only:
    - dev
    - staging
    - production

stages:
  - verify
  - framework
  - name: deploy
    if: NOT(type = pull_request)

jobs:
  include:
    - stage: verify
      name: unit_test
      script:
        - bundle install
        - bundle exec fastlane unit_test
    - stage: verify
      name: ui_test
      script:
        - bundle install
        - bundle exec fastlane ui_test
    - stage: verify
      name: lint
      addons:
        homebrew:
          taps: apptentive/travis
          packages:
          - swift-format-5.3
      script:
        - bundle exec fastlane lint
    - stage: framework
      name: xcframework
      addons:
        artifacts:
          paths:
            - $(ls *.zip | tr "\n" ":")
      script:
        - bundle install
        - BUILD_NUMBER=$TRAVIS_BUILD_NUMBER bundle exec fastlane framework
        - bundle exec fastlane zipArtifacts
        - export TRAVIS_TAG="$(agvtool what-marketing-version -terse1)-${TRAVIS_BRANCH}+${TRAVIS_BUILD_NUMBER}"
        - git tag $TRAVIS_TAG
    - stage: deploy
      name: testflight
      script:
        - bundle install
        - BUILD_NUMBER=$TRAVIS_BUILD_NUMBER bundle exec fastlane beta
    - stage: test
      name: integration_test
      script:
        - bundle install
        - bundle exec fastlane integration_test_production
